init:
  - git config --global core.autocrlf input

build:
  verbosity: detailed

os: Visual Studio 2017
before_build:
  - ps: Install-Product node
  - npm install yarn

build_script:
  - cmd: build.cmd

test: off
version: 0.{build}
  
 